ARG version=8
FROM centos:${version}
RUN yum -y update
RUN yum -y install dbus gjs sudo xorg-x11-server-Xvfb
RUN dbus-uuidgen > /var/lib/dbus/machine-id \
 && useradd -ms /bin/bash jiggle \
 && mkdir -p /home/jiggle/.local/share/gnome-shell/extensions/jiggle@jeffchannell.com
WORKDIR /home/jiggle/.local/share/gnome-shell/extensions/jiggle@jeffchannell.com
COPY . .
ENTRYPOINT [ "./entrypoint.sh" ]
